### ISSUE TITLE
Suggested way to add new model

### ISSUE THREAD

**Issue by drbh** [clifinger/canduma#1]
How would you suggest adding a new table (struct) to the app? for instance if I wanted each user to have "messages" how would I add that (to be inline with the overall app and API)

Thanks

**Comment by clifinger** [comment]
Maybe you can use this link: https://dev.to/open-graphql/building-powerful-graphql-servers-with-rust-3gla the author did some examples :)

**Comment by clifinger** [comment]
@drbh You can also check my PR #2  specially about the security in the Readme
