### ISSUE TITLE
Consider Heroku compatibility

### ISSUE THREAD

**Issue by satvikpendem** [clifinger/canduma#31]
I like this project as it's a really easy to use boilerplate for Rust projects. I use Heroku sometimes and also Dokku/Docker so it would be nice to easily use canduma with Heroku instead of building it myself.

Edit: So I was able to use the buildpack at https://github.com/emk/heroku-buildpack-rust to build canduma on Dokku on a DigitalOcean droplet. Since it uses Heroku buildpacks, this should be compatible with Heroku as well. Looks like there may be some bugs with the buildpack on Heroku's buildpack library, so use the full https://github.com/emk/heroku-buildpack-rust url instead when adding the buildpack.

Heroku: `heroku buildpacks:set https://github.com/emk/heroku-buildpack-rust.git`
Dokku: `dokku buildpacks:add https://github.com/emk/heroku-buildpack-rust.git`

If you don't set the buildpack as being Rust based, Heroku/Dokku assume it's a NodeJS app due to the `package.json` in the directory, and the build will fail. Actually, why is there a `package.json` in the project anyway? Looks like it's used for linting and testing, but I'm not sure what parts are JS based exactly.

**Comment by clifinger** [comment]
Hi @satvikpendem, I confirm that I use https://github.com/emk/heroku-buildpack-rust and It was worked for me. you can see the procfile in the code. Feel free to t do a PR !
