### ISSUE TITLE
Connection pooling via r2d2 crate

### ISSUE THREAD

**Issue by espnicholas** [clifinger/canduma#4]
The project could get a boost in performance by utilizing connection pools with r2d2 and Postgres. This is already flagged as a feature within the cargo.toml for diesel.

This is something most likely I could support with a PR, but wanted to have a discussion for desire before implementing.

**Comment by espnicholas** [comment]
Looking further, looks like r2d2 is being used. Mistake :).

**Comment by clifinger** [comment]
@espnicholas :) Feel free to take some open issues and PR
